import { Inter } from 'next/font/google';
import './globals.css';
// import Cuadrito from './ui/main/cuadrito';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Cuadrito /> */}
        {children}
      </body>
    </html>
  );
}
